### ISSUE TITLE
Meta-issue: TODOs before development

### ISSUE THREAD

**Issue by Kukovec** [freespek/solarkraft#6]
Here, we collect items that need to be addressed before starting development.

- [x] High-level architecture design: #1 
- [x] Small PoC/HOWTO for retrieving State: #4 
- [x] Small PoC/HOWTO for reading transaction data
- [ ] Integration experiment; Deploying a local network and RPC server [as described here](https://developers.stellar.org/network/soroban-rpc/admin-guide#run-your-own-instance-for-development), then deploying a custom contract and reading its state and transactions as described above.

**Comment by thpani** [comment]
I think we did all of this
